spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox?currentSchema=outbox
    username: outbox_application
    password: outbox_application_password
  flyway:
    url: jdbc:postgresql://localhost:5432/outbox?currentSchema=outbox
    user: outbox_application
    password: outbox_application_password
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: ''
