spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/outbox
    user: postgres
    password: postgres
    enabled: true
